default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ncmose_development


test:
  <<: *default
  database: ncmose_test

production:
  <<: *default
  database: ncmose_production
  username: ncmose
  password: <%= ENV['NCMOSE_DATABASE_PASSWORD'] %>
